---
#Notes:
#  1. This setup connect to cCloud. env Variables support the api-key, Same works for on-prem
#  2. Volume mounts at the end of this file is important to mount files from local to docker computer.
#     -  Download jar file of custom connectors to /data/tmp and use local confluent bub install command.
#     -  Datagen connector can be setup with custom schema.
#     -  Custom Schema have to loaded to mnt drive so that all workers have access to custom schema.
version: '2'
services:
  kafka-connect:
    image: confluentinc/cp-server-connect-base:7.3.0
    container_name: kafka-connect
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "${CCLOUD_KAFKA_BOOTSTRAP_SERVER}"
      CONNECT_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      CONNECT_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_SASL_MECHANISM: PLAIN
      CONNECT_SASL_JAAS_CONFIG: "${CCLOUD_SASL_JAAS_CONFIG}"
      CONNECT_REST_PORT: 8083
      CONNECT_REQUEST_TIMEOUT_MS: 20000
      CONNECT_RETRY_BACKOFF_MS: 500
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: _docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: _docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: _docker-connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
 #     CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
#      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "${SCHEMA_REGISTRY_URL}"
#      CONNECT_VALUE_CONVERTER_BASIC_AUTH_CREDENTIALS_SOURCE: "${SCHEMA_BASIC_AUTH_CREDENTIALS_SOURCE}"
#      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO: "${SCHEMA_REGISTRY_BASIC_AUTH_USER_INFO}"
      CONNECT_REST_ADVERTISED_HOST_NAME: "kafka-connect"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_LOG4J_APPENDER_STDOUT_LAYOUT_CONVERSIONPATTERN: "[%d] %p %X{connector.context}%m (%c:%L)%n"
      CONNECT_LOG4J_LOGGERS: "org.apache.kafka.connect.runtime.rest=WARN,org.reflections=ERROR"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "3"
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "3"
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "3"
      CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components/'
      CONNECT_LOG4J_ROOT_LOGLEVEL: INFO
      CONNECT_LOG4J_LOGGERS: org.reflections=ERROR
      CONNECT_PRODUCER_BOOTSTRAP_SERVERS: "${CCLOUD_KAFKA_BOOTSTRAP_SERVER}"
      CONNECT_PRODUCER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
      CONNECT_PRODUCER_SASL_JAAS_CONFIG: "${CCLOUD_SASL_JAAS_CONFIG}"
      CONNECT_PRODUCER_REQUEST_TIMEOUT_MS: 20000
      CONNECT_PRODUCER_RETRY_BACKOFF_MS: 500
      CONNECT_CONSUMER_BOOTSTRAP_SERVERS: "${CCLOUD_KAFKA_BOOTSTRAP_SERVER}"
      CONNECT_CONSUMER_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "https"
      CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_SSL
      CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
      CONNECT_CONSUMER_SASL_JAAS_CONFIG: "${CCLOUD_SASL_JAAS_CONFIG}"
      CONNECT_CONSUMER_REQUEST_TIMEOUT_MS: 20000
      CONNECT_CONSUMER_RETRY_BACKOFF_MS: 500
    command:
      - bash
      - -c
      - |
        echo "Installing connector plugins"
        #confluent-hub install --no-prompt jcustenborder/kafka-connect-transform-xml:0.1.0.20
        #confluent-hub install --no-prompt streamthoughts/kafka-connect-file-pulse:2.9.0
        confluent-hub install --no-prompt confluentinc/kafka-connect-datagen:0.6.0
        #confluent-hub install --no-prompt mdrogalis/voluble:0.3.1
        #confluent-hub install --no-prompt mongodb/kafka-connect-mongodb:1.3.0
        #confluent-hub install --no-prompt confluentinc/kafka-connect-ibmmq:11.0.11
        #
        # Copy IBM MQ jars from the shared volume
        #cp -v /tmp/jars/* /usr/share/confluent-hub-components/confluentinc-kafka-connect-ibmmq/lib/
        confluent-hub install --no-prompt /tmp/streamthoughts-kafka-connect-file-pulse-2.9.0.zip
        #
        # -----------
        # Launch the Kafka Connect worker
        /etc/confluent/docker/run &
        #
        # Don't exit
        sleep infinity
    volumes:
      - $PWD/data:/data
      - $PWD/data/tmp:/tmp
#      - mq-jars:/tmp/jars